# WineType Classification using Multiple Algorithms

In [1]:
import pandas as pd

In [2]:
original_training=pd.read_csv(".\\winedata.csv") 
original_training.head(10)

,Type,Alcohol,Malic,Ash,Alcalinity,Magnesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735
5,1,14.20,1.76,2.45,15.2,112,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450
6,1,14.39,1.87,2.45,14.6,96,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290
7,1,14.06,2.15,2.61,17.6,121,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295
8,1,14.83,1.64,2.17,14.0,97,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045
9,1,13.86,1.35,2.27,16.0,98,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045

In [3]:
X=original_training.copy()

del X['Type']
X.head()
#print(X)

,Alcohol,Malic,Ash,Alcalinity,Magnesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline
0,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [4]:
y = []

for data in original_training ['Type']:
    y.append(data)
    
print(y)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [5]:
from sklearn.naive_bayes import MultinomialNB
clf=MultinomialNB()
clf.fit(X.abs(),y)

#BernoulliNB() 
#MultinomialNB() 
#GaussianNB() 

"""
# import desiciontree classifier
from sklearn.tree import DecisionTreeClassifier  
clf = DecisionTreeClassifier()  
clf.fit(X.abs(),y) 

"""

"""
# import support vector machine classifier
from sklearn.svm import SVC # "Support Vector Classifier"
clf = SVC(kernel='poly', degree=9)

#kernel='poly', degree=9 will give you 0.81 accuracy
#kernel='sigmoid' will give you little over 0.5454 accuracy
#kernel='linear' as the kernel gives less than 0.4545 accuracy
#kernel='rbf' will give you 0.09 accuracy

#fitting x samples and y classes
clf.fit(X.abs(),y)

"""
#you can uncomment each of the above models and use them

'\n# import support vector classifier\nfrom sklearn.svm import SVC # "Support Vector Classifier"\nclf = SVC(kernel=\'poly\', degree=9)\n\n#kernel=\'poly\', degree=9 will give you 0.81 accuracy\n#kernel=\'sigmoid\' will give you little over 0.5454 accuracy\n#kernel=\'linear\' as the kernel gives less than 0.4545 accuracy\n#kernel=\'rbf\' will give you 0.09 accuracy\n\n#fitting x samples and y classes\nclf.fit(X.abs(),y)\n\n'

In [6]:
test_data= pd.read_csv(".\\winedata_test.csv")
X_test=test_data.copy()
del X_test['Type']
X_test.head(8)

,Alcohol,Malic,Ash,Alcalinity,Magnesium,Phenols,Flavanoids,Nonflavanoids,Proanthocyanins,Color,Hue,Dilution,Proline
0,13.48,1.81,2.41,20.5,100,2.70,2.98,0.26,1.86,5.10,1.04,3.47,920
1,13.28,1.64,2.84,15.5,110,2.60,2.68,0.34,1.36,4.60,1.09,2.78,880
2,13.05,1.65,2.55,18.0,98,2.45,2.43,0.29,1.44,4.25,1.12,2.51,1105
3,13.07,1.50,2.10,15.5,98,2.40,2.64,0.28,1.37,3.70,1.18,2.69,1020
4,14.22,3.99,2.51,13.2,128,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760
5,13.56,1.71,2.31,16.2,117,3.15,3.29,0.34,2.34,6.13,0.95,3.38,795
6,13.41,3.84,2.12,18.8,90,2.45,2.68,0.27,1.48,4.28,0.91,3.00,1035
7,12.21,1.19,1.75,16.8,151,1.85,1.28,0.14,2.50,2.85,1.28,3.07,718

In [7]:
Y_test=[]
for t_data in test_data ['Type']:
    Y_test.append(t_data)
print('actual test data sets labels')    
print(Y_test)

actual test data sets labels
[1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3]

In [8]:
print('predicted labels by the model')
print(clf.predict(X_test))

predicted labels by the model
[1 1 1 1 2 3 1 2 1 2 2 2 1 2 2 2 3 3 3 3 3 3 3 3]

In [9]:
from sklearn.metrics import accuracy_score
accuracy_score(Y_test, clf.predict(X_test))*100

83.33333333333334